
CREATE TABLE libros (
IdLibro INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Titulo VARCHAR(200) NOT NULL,
Autor VARCHAR(100) NOT NULL,
AnioPublicacion INT NOT NULL,
Categoria VARCHAR(100) NOT NULL,
Precio DECIMAL(10,2) NOT NULL
)

